project_id = "xefpvcwvnvavtlajyyxu"

[functions.notify-moderators]
verify_jwt = false

[functions.send-calendar-email]
verify_jwt = false

[functions.smart-reminders]
verify_jwt = true

[functions.push-notifications]
verify_jwt = true
